version: '3.8'

services:
  jarvis-backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://jarvis:jarvis123@postgres:5432/jarvis_db
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - jarvis-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - jarvis-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: jarvis_db
      POSTGRES_USER: jarvis
      POSTGRES_PASSWORD: jarvis123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - jarvis-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - jarvis-backend
    restart: unless-stopped
    networks:
      - jarvis-network

volumes:
  redis_data:
  postgres_data:

networks:
  jarvis-network:
    driver: bridge
